# steps:
# - name: 'gcr.io/cloud-builders/git'
#   secretEnv: ['SSH_KEY']
#   entrypoint: 'bash'
#   args:
#   - -c
#   - |
#     echo "$$SSH_KEY" >> /root/.ssh/id_rsa
#     chmod 400 /root/.ssh/id_rsa
#     cp known_hosts_annie_github /root/.ssh/known_hosts
#   volumes:
#   - name: 'ssh'
#     path: /root/.ssh

# - name: 'gcr.io/cloud-builders/git'
#   args:
#   - clone
#   - git@github.com:AnnieBem/demo_node_build
# volumes:
# - name: 'ssh'
#   path: /root/.ssh
# availableSecrets:
#   secretManager:
#   - versionName: projects/myfirstproject-304920/secrets/Annie-git/versions/latest
#     env: 'SSH_KEY'


# Access the id_github file from Secret Manager, and setup SSH
steps:
- name: 'gcr.io/cloud-builders/git'
  secretEnv: ['SSH_KEY']
  entrypoint: 'bash'
  args:
  - -c
  - |
    echo "$$SSH_KEY" >> /root/.ssh/id_rsa
    chmod 400 /root/.ssh/id_rsa
    cp known_hosts_annie_github /root/.ssh/known_hosts
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Clone the repository
- name: 'gcr.io/cloud-builders/git'
  args:
  - clone
  - git@github.com:AnnieBem/demo_node_build

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}','.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}']

- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image','deployment/${_DEPLOYMENTNAME}','${_CONTAINERNAME}=gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'

substitutions:
    _PROJECT: myfirstproject-304920
    _ZONE: us-central1-a
    _GKE_CLUSTER: my-first-cluster-1

    _DEPLOYMENTNAME: hello-world-service
    _CONTAINERNAME: demo-node-build-1
    _REPO_NAME: github_anniebem_demo_node_build


    _VERSION: v1.0
options:
    substitution_option: 'ALLOW_LOOSE'

volumes:
- name: 'ssh'
  path: /root/.ssh
availableSecrets:
  secretManager:
  - versionName: projects/myfirstproject-304920/secrets/Annie-git/versions/latest
    env: 'SSH_KEY'

