steps:

#Access git pvt key from Secret Manager using GCP sdk command and put it into local .ssh folder 
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: ['-c', 'gcloud secrets versions access latest --secret=annie-git-pvt > /root/.ssh/id_rsa']
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Add github.com domain name to known_hosts inside .ssh folder, also change permission of pvt key file
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - -c
  - |
    chmod 600 /root/.ssh/id_rsa
    cat <<EOF >/root/.ssh/config
    Hostname github.com
    IdentityFile /root/.ssh/id_rsa
    EOF
    ssh-keyscan -t rsa github.com > /root/.ssh/known_hosts
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Clone the repository
- name: 'gcr.io/cloud-builders/git'
  args:
  - clone
  - git@github.com:AnnieBem/demo_node_build
  volumes:
  - name: 'ssh'
    path: /root/.ssh


- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}','.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}']

- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image','deployment/${_DEPLOYMENTNAME}','${_CONTAINERNAME}=gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'

substitutions:
    _PROJECT: myfirstproject-304920
    _ZONE: us-central1-a
    _GKE_CLUSTER: my-first-cluster-1

    _DEPLOYMENTNAME: hello-world-service
    _CONTAINERNAME: demo-node-build-1
    _REPO_NAME: github_anniebem_demo_node_build


    _VERSION: latest
options:
    substitution_option: 'ALLOW_LOOSE'



