steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}','.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}']

- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image','deployment/${_DEPLOYMENTNAME}','${_CONTAINERNAME}=gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'

substitutions:
    _PROJECT: myfirstproject-304920
    _ZONE: us-central1-a
    _GKE_CLUSTER: my-first-cluster-1

    _DEPLOYMENT: nodedeploy
    _CONTAINERNAME: nodedeploy

    _VERSION: v1.0
options:
    substitution_option: 'ALLOW_LOOSE'